### ISSUE TITLE
Movie carousels should not resize

### ISSUE THREAD

**Issue by jajmo** [jajmo/Ghetto-IMDB#17]
On the Sci-Fi carousel, when you hit the right or left arrow it resizes to adjust to the largest cover. The size of the carousel should remain constant, presumably to the size of the largest cover.

**Comment by patgrasso** [comment]
The covers should be of constant size as well. Regardless, the carousel should have a fixed height, otherwise there might be inconsistencies between the various carousels, which would also be bad.

**Comment by patgrasso** [comment]
This was closed a while ago

**Comment by patgrasso** [comment]
This was fixed a while ago.
