### ISSUE TITLE
Can't click movie links

### ISSUE THREAD

**Issue by jajmo** [jajmo/Ghetto-IMDB#34]
On the homepage, movie links can't be clicked. (this will be relevant when the single movie view is merged)

**Comment by patgrasso** [comment]
This is caused by one of bootstrap's click event handlers for the carousel. For some reason, it calls `preventDefault()` on any click event whose target is missing the `data-target` attribute. Giving the carousel that attribute solves the issue. I also changed the styling for links on overlays.

**Comment by jajmo** [comment]
Perfect, thanks for fixing this Pat.
